<?php
/**
 * setup.php — One-click database installer
 *
 * Open this file in your browser BEFORE using the system.
 * It will:
 *  1. Connect to MySQL with the credentials you provide
 *  2. Create the 'hrms' database if it doesn't exist
 *  3. Run the full schema from config/database.sql
 *  4. Rewrite config/db.php with your credentials
 *  5. Redirect you to the login page
 *
 * Default admin after setup:
 *   Email:    admin@hrms.com
 *   Password: password
 */

$error   = '';
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $host   = trim($_POST['host']    ?? 'localhost');
    $dbUser = trim($_POST['db_user'] ?? 'root');
    $dbPass = $_POST['db_pass']      ?? '';
    $dbName = trim($_POST['db_name'] ?? 'hrms');

    // ── Attempt connection ────────────────────────────────────
    $conn = @new mysqli($host, $dbUser, $dbPass);

    if ($conn->connect_error) {
        $error = 'Connection failed: ' . $conn->connect_error;
    } else {
        // Create database if missing
        $conn->query("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $conn->select_db($dbName);

        // Run SQL schema — split on semicolon, skip USE/CREATE DATABASE lines
        $sql        = file_get_contents(__DIR__ . '/config/database.sql');
        $statements = array_filter(array_map('trim', explode(';', $sql)));

        foreach ($statements as $stmt) {
            if (!$stmt) continue;
            // Skip statements handled above
            if (stripos($stmt, 'CREATE DATABASE') !== false) continue;
            if (stripos($stmt, 'USE ')            !== false) continue;
            // Execute; ignore "already exists" errors (codes 1050 duplicate table, 1060 duplicate column)
            if (!$conn->query($stmt) && !in_array($conn->errno, [1050, 1060, 1061, 1062])) {
                // Non-fatal: log but continue
                error_log("HRMS setup SQL warning [{$conn->errno}]: " . $conn->error);
            }
        }

        // ── Rewrite config/db.php with supplied credentials ──
        $configContent = <<<PHP
<?php
// Database credentials — auto-generated by setup.php
define('DB_HOST', '{$host}');
define('DB_USER', '{$dbUser}');
define('DB_PASS', '{$dbPass}');
define('DB_NAME', '{$dbName}');
PHP;
        // Append rest of db.php (the bootstrap file handles classes; db.php just holds defines)
        file_put_contents(__DIR__ . '/config/db.php', $configContent);

        $success = true;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>HRMS Setup</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<link href="assets/css/style.css" rel="stylesheet">
</head>
<body class="setup-page">

<div class="setup-card">

  <!-- Header -->
  <div class="text-center mb-4">
    <div style="width:60px;height:60px;background:linear-gradient(135deg,#2c3e7a,#4f6af0);
                border-radius:12px;display:flex;align-items:center;justify-content:center;
                color:#fff;font-size:1.8rem;font-weight:700;margin:0 auto 12px">H</div>
    <h4 class="fw-700" style="color:#1a2456">HRMS Setup</h4>
    <p class="text-muted fs-sm mb-0">Configure your database connection to get started</p>
  </div>

  <?php if ($success): ?>
    <!-- ── Success state ── -->
    <div class="alert alert-success">
      <i class="bi bi-check-circle-fill me-2"></i>
      <strong>Setup complete!</strong> Database created and schema imported.
    </div>
    <div class="card bg-light mb-3">
      <div class="card-body py-2">
        <div class="fs-sm">
          <strong>Default Admin Login</strong><br>
          Email: <code>admin@hrms.com</code><br>
          Password: <code>password</code>
        </div>
      </div>
    </div>
    <a href="index.php" class="btn btn-primary w-100">
      <i class="bi bi-box-arrow-in-right me-2"></i>Go to Login
    </a>

  <?php else: ?>
    <!-- ── Setup form ── -->
    <?php if ($error): ?>
      <div class="alert alert-danger fs-sm">
        <i class="bi bi-exclamation-triangle me-1"></i><?= htmlspecialchars($error) ?>
      </div>
    <?php endif; ?>

    <form method="POST">
      <div class="mb-3">
        <label class="form-label form-label-sm">Database Host</label>
        <input type="text" name="host" class="form-control form-control-sm"
               value="<?= htmlspecialchars($_POST['host'] ?? 'localhost') ?>" required>
        <div class="form-text fs-xs">Usually <code>localhost</code> for XAMPP/WAMP</div>
      </div>
      <div class="mb-3">
        <label class="form-label form-label-sm">MySQL Username</label>
        <input type="text" name="db_user" class="form-control form-control-sm"
               value="<?= htmlspecialchars($_POST['db_user'] ?? 'root') ?>" required>
      </div>
      <div class="mb-3">
        <label class="form-label form-label-sm">MySQL Password
          <span class="text-muted">(leave blank if none)</span>
        </label>
        <input type="password" name="db_pass" class="form-control form-control-sm">
      </div>
      <div class="mb-4">
        <label class="form-label form-label-sm">Database Name</label>
        <input type="text" name="db_name" class="form-control form-control-sm"
               value="<?= htmlspecialchars($_POST['db_name'] ?? 'hrms') ?>" required>
        <div class="form-text fs-xs">Will be created automatically if it doesn't exist</div>
      </div>
      <button type="submit" class="btn btn-primary w-100">
        <i class="bi bi-database-gear me-2"></i>Install & Continue
      </button>
    </form>

    <!-- Tip box -->
    <div class="mt-3 p-3 fs-xs text-muted"
         style="background:#f8f9ff;border-radius:8px;border:1px solid #e5e7eb">
      <i class="bi bi-lightbulb me-1 text-warning"></i>
      <strong>Tip:</strong> After setup, delete or rename <code>setup.php</code>
      to prevent others from re-running the installer.
    </div>
  <?php endif; ?>

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
